### PR TITLE
Compat with old version when upgrading plugin

### LINKED ISSUE #134: Downloading of artefacts from 0.3.5 broken after upgrade to 0.3.10
It appears `<storageType>` became a mandatory value for builds somewhere between 0.3.5 and 0.3.10. Clicking a link from an old build after upgrading the plugin throws an error:

```
    Error occurred while downloading artifact null
```

This means hundreds of thousands of builds now no longer have functional download capability.

After some investigation, we found that adding:

```
      <storageType>blobstorage</storageType>
```

inside the `<com.microsoftopentechnologies.windowsazurestorage.AzureBlobAction plugin="windows-azure-storage@0.3.5">` section of old build.xml files fixed downloadability - but this shouldn't be needed. A plugin update shouldn't break our existing builds.

### PR DESCRIPTION
**Pull request by gavinfish**
Fix #134 . Use get**Type() methods to give default value of blob storage since the previous version only support blobs.

### CODE REVIEW

File: src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java [hunk 1]
```diff
@@ -171,4 +171,11 @@ public boolean isAnonymousAccess(Authentication auth) {
     public Api getApi() {
         return new Api(this);
     }
+
+    public String getStorageType() {
+        if (Constants.FILE_STORAGE.equals(storageType)) {
```
Comment (yungezz) [inline src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java]: if storageType not null?

File: src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java [hunk 2]
```diff
@@ -175,7 +175,10 @@ public String getStorageAccName(Item owner) {
     }
 
     public String getDownloadType() {
-        return downloadType;
+        if (DOWNLOAD_TYPE_FILE_SHARE.equals(downloadType) || DOWNLOAD_TYPE_PROJECT.equals(downloadType)) {
```
Comment (yungezz) [inline src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureStorageBuilder.java]: if downloadType not null?

File: src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java (hunk 1 above)
Comment (gavinfish) [reply src/main/java/com/microsoftopentechnologies/windowsazurestorage/AzureBlobAction.java]: "blob".equals(null) will return false
